version: '3.9'

services:
  app_test:
    build: .
    container_name: library_app_test
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_test:5432/librarydb_test?schema=public"
    depends_on:
      postgres_test:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npx jest --runInBand"]
    networks:
      - test-network

  postgres_test:
    image: postgres:17
    container_name: library_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarydb_test
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d librarydb_test"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test-network:
    driver: bridge